<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Draxayani-PC" name="com.adv.qa.selenium.tests.currency.phase2.A088_Authorisation_By_Val_Or_GL_ResponsibilityTest" tests="1" failures="1" timestamp="5 Sep 2014 09:40:37 GMT" time="769.963" errors="0">
  <testcase name="verify" time="769.963" classname="com.adv.qa.selenium.tests.currency.phase2.A088_Authorisation_By_Val_Or_GL_ResponsibilityTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.verify() didn&#039;t finish within the time-out 800000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.verify() didn't finish within the time-out 800000
	at java.lang.Thread.sleep(Native Method)
	at com.adv.qa.selenium.helpers.WaitHelper.waitAdditional(WaitHelper.java:222)
	at com.adv.qa.selenium.framework.pageObjects.currency.CurrencyPage.enterValueORGLResponsibilityForAP(CurrencyPage.java:5672)
	at com.adv.qa.selenium.tests.currency.phase2.A088_Authorisation_By_Val_Or_GL_ResponsibilityTest.createAuthorisationByGLResponsibility(A088_Authorisation_By_Val_Or_GL_ResponsibilityTest.java:82)
	at com.adv.qa.selenium.tests.currency.phase2.A088_Authorisation_By_Val_Or_GL_ResponsibilityTest.verify(A088_Authorisation_By_Val_Or_GL_ResponsibilityTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verify -->
</testsuite> <!-- com.adv.qa.selenium.tests.currency.phase2.A088_Authorisation_By_Val_Or_GL_ResponsibilityTest -->
